### ISSUE TITLE
Issue Annotating Raw KEGG Map

### ISSUE THREAD

**Issue by Ramirj** [noriakis/ggkegg#11]
Hi @noriakis,

I'm trying to highlight specific gene nodes on raw KEGG maps using ggkegg but for some reason it isn't working for me. Is it possible to achieve this using this package? This is the code that I tried to use:

reaction <- c("rn:R00756")
g <- pathway("dosa00010") |> mutate(mod=highlight_set_nodes(reaction, how="all"))
ggraph(g, layout="manual", x=x, y=y)+
  geom_node_rect(fill="grey",aes(filter=type == "ortholog"))+
  overlay_raw_map("dosa00010")+
  geom_node_point(aes(filter=type == "reaction"),
                  shape=21, fill="blue", color="black", size=2)+
  ggfx::with_outer_glow(
    geom_node_point(aes(filter=mod, x=x, y=y), color="red",size=2),
    colour="yellow",expand=5
  )+
  theme_void()

And this is the resulting plot:
<img width="1440" alt="Screenshot 2023-11-30 at 4 11 40 PM" src="https://github.com/noriakis/ggkegg/assets/148665071/6e53130b-ea77-45f9-9c5a-674a1e7c6fdf">

I didn't receive any error messages or anything, but the gene node that I wanted to highlight was not highlighted. If you could provide some insight that would be great. Thank you!

**Comment by noriakis** [comment]
Hi, `highlight_set_nodes` searches for the `name` column in node data by default as described in the manual. You should change `name` argument to `reaction` if you search for the `reaction` column, like:

```r
highlight_set_nodes(highlight_reaction, name="reaction", how="all")
```

I think raising the warning or the message could be useful if none of the nodes is highlighted. I will update the feature  in `dev`.

**Comment by noriakis** [comment]
In `highlight_set_nodes` of the `devel` branch, the message will be shown when there are no nodes highlighted (or all nodes are highlighted). Feel free to reopen the issue if you encounter the other issue.

commit 12587f486db195a2ca5056081744bddb34922b31
