### ISSUE TITLE
Mapping genes to KEGG Pathways Using KO numbers

### ISSUE THREAD

**Issue by Ramirj** [noriakis/ggkegg#18]
Hi @noriakis,

Is there any way to map genes to KEGG Pathways using KO numbers with ggkegg? I'm trying to map genes with LFCs to the "Plant hormone signal transduction" pathway. Any help would be appreciated, thank you.

**Comment by noriakis** [comment]
Hi @Ramirj, Thank you for the inquiry. If you can convert your gene IDs to IDs specified in your selected organism's "Plant hormone signal transduction" pathway, it can be accomplished using any function such as `dplyr::mutate`.

**Comment by Ramirj** [comment]
Hi @noriakis, I have the gene IDs specified in the "Plant hormone signal transduction" pathway for my organism, but I'm not sure how to use the mutate function to map my genes to the pathway. Could you provide an example? Thank you.
