### ISSUE TITLE
Analyzing gene data using ggkegg

### ISSUE THREAD

**Issue by Ramirj** [noriakis/ggkegg#2]
Hello @noriakis,

I was wondering if it was possible to analyze my own genetic data with this tool using RAP.ID's? For example, the RAP.ID for one of the genes i'm analyzing is "Os01g0124200". All of my data is on an excel spreadsheet. Thank you for your help!

**Comment by noriakis** [comment]
Hi @Ramirj,

Yes, you can analyze your own genetic data if you could convert your identifiers to one listed in KEGG (or other identifiers that can be converted to the EC numbers).

**Comment by Ramirj** [comment]
@noriakis Do you know of a script or other resource that can achieve this? Sorry, I'm very new to coding. If not then no worries!

**Comment by noriakis** [comment]
@Ramirj I'm sorry, but I have no experience in analyzing this species, and it's probably better to ask elsewhere how to convert the IDs.

**Comment by Ramirj** [comment]
Okay, thank you for all of your help!

**Comment by Ramirj** [comment]
@noriakis Okay so I was able to find identifiers that can be converted to EC numbers for my genes. Now I'm just trying to find a way to map these IDs onto the glycolysis pathway for Oryza Sativa. I tried modifying the script you made previously but received this error code: 

"Error in `collect()`:
! Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
Run `rlang::last_trace()` to see where the error occurred."

Do you know what could be causing this issue? Here is a picture of my code for reference:
<img width="1440" alt="Screenshot 2023-10-30 at 12 10 52 AM" src="https://github.com/noriakis/ggkegg/assets/148665071/c3131256-9bd5-43bf-8a53-cdedcb4c858d">

Again, thank you so much for all of your help!
