### ISSUE TITLE
Missing cell membrane dashed lines

### ISSUE THREAD

**Issue by SZhengP** [noriakis/ggkegg#22]
Hi,

Thank you for this great package.

I wonder whether there is bug for the cell membrane lines generation or I did something wrong.

Here are my codes which are basically from your repo https://noriakis.github.io/software/ggkegg/pathway.html
The only difference is that I used a pathway showing the cell membrane: hsa05418

```
data(geneList, package='DOSE')
test <- geneList[1:100]
names(test) <- paste0("hsa:",names(test))
g <- pathway("hsa05418") |> 
  mutate(value1=node_numeric(test),
         value2=node_numeric(test),
         value3=node_numeric(test),
         value4=node_numeric(test))
res <- ggraph(g) + 
  geom_node_rect(aes(value1=value1)) + 
  geom_node_rect(aes(value2=value2, xmin=xmin+width/4))+
  geom_node_rect(aes(value3=value3, xmin=xmin+2*width/4))+
  geom_node_rect(aes(value4=value4, xmin=xmin+3*width/4))+
  overlay_raw_map() + theme_void() +
  scale_fill_multi(aesthetics = c("value1", "value2",
                                  "value3", "value4"),
                   name = list("Condition1",
                               "Condition2",
                               "Condition3",
                               "Condition4"),
                   colours = list(
                     scales::brewer_pal(palette = "YlGnBu")(6),
                     scales::brewer_pal(palette = "RdPu")(6),
                     scales::brewer_pal(palette = "PuOr")(6),
                     scales::brewer_pal(palette = "RdBu")(6)
                   ),
                   guide = guide_colorbar(barheight = unit(50, "pt")))
res
```
The figure does not show the cell membrane. 
![image](https://github.com/noriakis/ggkegg/assets/120602118/3468e290-db1c-4dec-a17f-8607f34843c3)

If I use pathview, it does shows the cell membrane lines.
![image](https://github.com/noriakis/ggkegg/assets/120602118/4cd5cc0b-8369-4119-b7da-74e02c7819e4)

Thank you!

Best,
Shijie

**Comment by noriakis** [comment]
Hi, thank you for reporting the issue.
By default, the `overlay_raw_map` function makes some colors used in the images transparent, and the grey color used for the membrane was one of them. I will remove this color from the default in the next version.

For now, you can specify the transparent colors without grey color in overlay_raw_map like:

```r
overlay_raw_map(transparent_colors=c("#FFFFFF", "#BFBFFF", "#BFFFBF"))
```

**Comment by noriakis** [comment]
Commit 8937dc5

**Comment by SZhengP** [comment]
Thank you so much! It fixes the issue.
