### ISSUE TITLE
"I would like to know why I encounter these missing values when plotting certain pathways?"

### ISSUE THREAD

**Issue by mondayz11** [noriakis/ggkegg#23]
Hello,
Thank you very much for creating such a great package for us to use. Before this, we could only draw manually with AI. When I try to use the package, I have some questions. Could you please help me with the following issue?
I want to use this package to draw the maize fatty acid synthesis metabolism graph, but it appears in such a way that there is no display. Could you please tell me the reason? Is it because the pathway is too large?
Thank you!
![Uploading dd8a42b82945006ce30f63994343aad.png…]()

**Comment by noriakis** [comment]
Hi, thanks for the report! Could you provide me with the codes you used to produce the figure?

**Comment by mondayz11** [comment]
Sorry, I've been busy lately and haven't logged in for a long time. My code is based on the example you provided, but I changed the path to zma00061

**Comment by mondayz11** [comment]
> 您好，感谢您的报告！你能向我提供你用来生成该图的代码吗？

Sorry, I've been busy lately and haven't logged in for a long time. My code is based on the example you provided, but I changed the path to zma00061

**Comment by noriakis** [comment]
Hi, thanks for the reply, but could you paste the code here as I cannot tell which example you tried?

**Comment by noriakis** [comment]
Hi, closing the issue but feel free to reopen it!
