### ISSUE TITLE
directory not work

### ISSUE THREAD

**Issue by joe-jhou2** [noriakis/ggkegg#24]
When I specify directory as "/xxxx/yyy/zz", the downloaded KGML files are not stored in the designated directory.

**Comment by joe-jhou2** [comment]
I should say this, when running highlight_module with pathway, the highlight_module download module files are not in the designated directory.

**Comment by noriakis** [comment]
Thanks for reaching out and I am sorry for the very late response. Could you provide the code? `highlight_module` itself does not download the module file.

**Comment by noriakis** [comment]
Hi, closing the issue but feel free to reopen it if the problem persists.
