### ISSUE TITLE
Cannot parse some pathways, bug report

### ISSUE THREAD

**Issue by wangshiming** [noriakis/ggkegg#30]
I encount some pathways that cannot be handled:

g <- pathway('ko00061', use_cache = TRUE)
g <- pathway('ko00261', use_cache = TRUE)
g <- pathway('ko00680', use_cache = TRUE)

Error in rbind(deparse.level, ...) :
  numbers of columns of arguments do not match

**Comment by noriakis** [comment]
Hi, thanks for reporting the bugs. It seems that those pathways can be parsed in the latest version (1.1.18).
It might be related to the version, and could you check the results after updating to the latest version?

**Comment by wangshiming** [comment]
Yes, the new version works. Thank you very much!
