### ISSUE TITLE
overlay_raw_map must download png

### ISSUE THREAD

**Issue by hanguojun007** [noriakis/ggkegg#32]
when i use `overlay_raw_map(directory = kegg_map_path, use_cache = FALSE)` , it always download png ,even if i have downlaod this png.

**Comment by noriakis** [comment]
Thank you very much for reporting this bug. As you stated, the `overlay_raw_map` did not use directory option (download the file irrespective of the option). I have now fixed the error and updated the version. Also, the `overlay_raw_map` now raises the error if the file does not exist in the directory. Please update the version by `devtools::install_github("noriakis/ggkegg")` if you are to use the new version.

Thanks again for reporting!

1cc92ed

**Comment by noriakis** [comment]
Closing but feel free to reopen if the problem persists.
