### ISSUE TITLE
highlight_entities: Missing "directiory" parameter

### ISSUE THREAD

**Issue by w2felix** [noriakis/ggkegg#37]
highlight_entities <- function(pathway, set, how="any",
	num_combine=mean, name="graphics_name", sep=", ", no_sep=FALSE,
	show_type="gene", fill_color="tomato", remove_dot=TRUE,
	legend_name=NULL, use_cache=FALSE, return_graph=FALSE)
	
misses the directory parameter to be able to work with local maps, without using the API

**Comment by noriakis** [comment]
Thank you very much for your comments and raising an important point. As you stated, `highlight_entities` function misses the `directory` parameter. I have now added one and pushed to the `devel` branch.

Thanks again for reporting.

**Comment by w2felix** [comment]
great :)
