### ISSUE TITLE
Export to igraph

### ISSUE THREAD

**Issue by ag1805x** [noriakis/ggkegg#39]
Is there a way to export the KEGG graph created within `ggkegg` as `igraph` object?

**Comment by noriakis** [comment]
Hi, thanks for the inquiry. ggkegg handles KEGG data using [`tbl_graph` class](https://tidygraph.data-imaginist.com/reference/tbl_graph.html). Thus, the graph created within ggkegg can be directly handled by `igraph` functions. Alternatively, you can use `as.igraph()` function for converting.
