### ISSUE TITLE
Script for mapping custom gene IDs using ggkegg

### ISSUE THREAD

**Issue by Ramirj** [noriakis/ggkegg#4]
Hi @noriakis,

I have an excel file with a list of EC codes that I would like to map to the glycolysis pathway for Oryza Sativa using the ggkegg package you created. However, when I try to run my code, the code doesn't run correctly. When I run your original code everything works fine, the issue only arises when I try to input my own EC numbers. If you could assist me in solving this problem it would be greatly appreciated. I'm very lost right now. Here is the code that I am trying to run:
<img width="1440" alt="Screenshot 2023-10-31 at 12 45 56 AM" src="https://github.com/noriakis/ggkegg/assets/148665071/e225ba0d-f58d-4fa2-b79c-832948d84c1b">

**Comment by noriakis** [comment]
Hi @Ramirj, Could you please tell me the error produced? Also, you do not need to paste the screenshot here, rather pasting the code itself helps a lot.

**Comment by Ramirj** [comment]
@noriakis Oh ok, apologies

Here is the script:
# Load the required libraries
library(ggkegg)
library(data.table)
library(BiocFileCache)
library(ggraph)
library(dplyr)


# Define your custom gene IDs (assuming merged_data4 has the relevant data)
custom_gene_ids <- EC_codes

# Fetch and cache RN to EC map
url <- "https://rest.kegg.jp/link/reaction/ec"
bfc <- BiocFileCache()
path <- bfcrpath(bfc, url)
convert <- data.table::fread(path, header = TRUE, sep = "\t")
rntoec <- setNames(convert$V2, convert$V1)

# Map the EC number to custom gene nodes
custom_gene_ec <- sapply(custom_gene_ids, function(gene_id) {
  ec <- rntoec[gene_id]
  if (length(ec) == 0) {
    ec <- "Unknown"
  }
  return(ec)
})

# Create a custom data frame for the pathway visualization
custom_data <- data.frame(
  name = custom_gene_ids,
  ec = custom_gene_ec,
  type = "gene"
)

# Visualize the pathway
g <- pathway("osa00010")

# Combine KEGG pathway data with custom gene data
gg <- g %>%
  bind_rows(custom_data)

# Visualize the pathway with custom gene IDs
ggplot(gg) +
  geom_edge_link(aes(color = subtype_name)) +
  geom_node_point(aes(filter = type == "compound"), color = "lightblue") +
  geom_node_rect(aes(filter = type == "gene"), fill = "lightpink") +
  geom_node_text(aes(label = ec, filter = type == "gene"), color = "black", size = 2) +
  geom_node_text(aes(label = name, filter = type == "compound"), color = "grey50", size = 2, repel = TRUE) +
  theme_void()

Here is the error code I'm getting:
Error in `bind_rows()`:
! Argument 1 must be a data frame or a named atomic vector.
Run `rlang::last_trace()` to see where the error occurred.


I already have my own EC numbers for the genes that I'm interested in. I just want to map them to the glycolysis pathway for Oryza Sativa.

**Comment by noriakis** [comment]
@Ramirj Thanks for the update. As the error indicates, you should pass a data frame or a named vector to `bind_rows`. In this case, you should use `bind_nodes` if you are to add something to node data. Please see [here](https://tidygraph.data-imaginist.com/reference/bind_graphs.html) for graph manipulation. I cannot say how to because I don't have your data (`custom_gene_ids ` object).
Please kindly note that the Issue section here is for reporting the problems of `ggkegg` functions, and your question might be appropriate  elsewhere as it is related to the general data conversion problem.

**Comment by noriakis** [comment]
Feel free to reopen the issue if you have any problem like #1!
