### ISSUE TITLE
An error occurred when I attempted to install ggkegg.

### ISSUE THREAD

**Issue by losted-star** [noriakis/ggkegg#5]
![image](https://github.com/noriakis/ggkegg/assets/39818372/6cfa24e2-d58a-4479-ac5c-5917c30bac21)

![image](https://github.com/noriakis/ggkegg/assets/39818372/5c197227-bb1a-4791-a3e5-2620637a0b5b)

I attempted two methods as shown in the tutorial, but I was unable to successfully install ggkegg. What steps should I take to resolve this problem?

**Comment by losted-star** [comment]
I have resolved this issue by using the following code:
```shell
micromamba install r-stringi
```

**Comment by noriakis** [comment]
Hi @losted-star, Thank you for reporting the issue and I'm glad that the problem has been resolved.
For the latter installation method, `ggkegg` is currently available in `devel` or `3.18` version of Bioconductor.
