### ISSUE TITLE
Vignette Data

### ISSUE THREAD

**Issue by alabella19** [noriakis/ggkegg#8]
Would it be possible to have a copy of the "uro.deseq.res.rda" dataset to work through the vignette?

Best,
Abbe

**Comment by noriakis** [comment]
Hi @alabella19,

Thank you for the inquiry. I apologize for the inconvenience.

I was thinking of putting relevant data into a repository, but some files are large and I temporally share the `uro.deseq.res.rda` object at [this Dropbox link](https://www.dropbox.com/scl/fi/43uju9oso77r8qydm71fz/uro.deseq.res.rda?rlkey=e62sgpw9lsdjiknzy2tk14szs&dl=0). I will update the book codes not to use `load()` soon.

Sincerely,
Noriaki Sato

**Comment by alabella19** [comment]
Got it! Thank you so much for sharing.

Best,
Abbe
Dr. Abigail Leavitt LaBella
Assistant Professor
Department of Bioinformatics and Genomics
University of North Carolina at Charlotte

***@***.***
