### ISSUE TITLE
Pentose Phosphate Pathway Diagram

### ISSUE THREAD

**Issue by Ramirj** [noriakis/ggkegg#9]
Hi @noriakis,

I'm currently trying to visualize the "pentose phosphate" pathway in kegg using the ggkegg package, but when I create a diagram many of the nodes are not connected to each other, and it doesn't seem as large as the pentose phosphate pathway in KEGG. For example, here is a picture of the pathway diagram I made (top), and the pentose phosphate pathway within KEGG (bottom):

<img width="1440" alt="Screenshot 2023-11-17 at 10 16 22 PM" src="https://github.com/noriakis/ggkegg/assets/148665071/9bf2fd83-df85-4ab0-abfc-d0adb86660a3">

<img width="1440" alt="Screenshot 2023-11-17 at 10 17 11 PM" src="https://github.com/noriakis/ggkegg/assets/148665071/119261a1-d5ce-45fd-82dd-79a4a9f7c9ca">

Here is an example of my code as well, thank you for your help!

# Make Oryza Sativa pentose phosphate pathway diagram with LFCs for genes present in lab data

library(ggkegg)
library(BiocFileCache)

# Fetch and cache RN to EC map
url <- paste0("https://rest.kegg.jp/link/reaction/ec")
bfc <- BiocFileCache()
path <- bfcrpath(bfc, url)
convert <- data.frame(data.table::fread(path, header = FALSE, sep = "\t"))
rntoec <- convert$V1 |>
  strsplit(":") |>
  vapply("[", 2, FUN.VALUE = "a") |>
  setNames(convert$V2)
# Map the EC number to gene nodes
g <- pathway("dosa00030") |>
  mutate(ec = rntoec[reaction])
# Define a vector of node names to highlight
nodes_to_highlight <- R_Numbers

# Add LFCs

# Create a vector containing log fold changes
LFC_vector <- LFCs

# Add log fold changes to the graph
g <- g %>%
  mutate(genes_of_interest = ifelse(reaction %in% nodes_to_highlight, LFC_vector, NA))

# Add color gradient to visualize LFCs

gg <- g |>
  filter(type %in% c("compound", "gene")) |>
  ggraph(layout = "manual", x = x, y = y) +
  geom_edge_link(aes(color = subtype_name)) +
  geom_node_rect(aes(fill = genes_of_interest), size = 5) +
  geom_node_shadowtext(aes(label = ec, filter = type == "gene"), color = "black",
                       bg.colour = "white", size = 2) +
  geom_node_text(aes(label = name, filter = type == "compound"),
                 color = "grey50", size = 2, repel = TRUE) +
  scale_fill_viridis_c(option = "viridis", direction = 1, begin = 1.0, end = 1.0) +  # Customize color scale
  theme_void()

gg

**Comment by noriakis** [comment]
Hi @Ramirj,

Thank you for the inquiry. One possible reason would be that you are filtering nodes with `filter(type %in% c("compound", "gene"))`, so plotting all the nodes would help. Also, the structure in the pathway differs from species to species (organism-specific pathways, see [here](https://www.genome.jp/kegg/xml/docs/)) and not all the edges in the reference pathway would be drawn in the organism-specific pathways. If you notice any nodes or edges that are present in KGML but not in the resulting graph, please kindly report them here.
